### ISSUE TITLE
Fixed time scheduler

### ISSUE THREAD

**Issue by Olegt0rr** [aio-libs/aiojobs#12]
If you wanna improve your scheduler, add feature with fixed time.

schedule.every(10).minutes.do(job, *args, **kwargs)
schedule.every(2).hours.do(job, *args, **kwargs)
schedule.every().day.at("10:30").do(job, *args, **kwargs)
schedule.every().monday.do(job, *args, **kwargs)
schedule.every().wednesday.at("13:15").do(job, *args, **kwargs)

**Comment by asvetlov** [comment]
There is https://github.com/gawel/aiocron
Now sure if I need duplicate it

**Comment by kxepal** [comment]
+1 to @asvetlov point. No need to make this project complicated. Periodic tasks would eventually need locks (since they may hang and you don't want to run the same job twice) and then you would need distributed locks since your app is scaled. And then you would need task dependencies and so on and so on.
