### ISSUE TITLE
The task "_failed_task" may be already done in the method close

### ISSUE THREAD

**Issue by matemax** [aio-libs/aiojobs#127]
It seems, The task "_failed_task"  may mark as done (cancelled) in a case of shutdown service. And the folllowing line would be does not correct (probably):

https://github.com/aio-libs/aiojobs/blob/074ce36e0cade929481b87a97990a6946e31341f/aiojobs/_scheduler.py#L100

We can check "_failed_task.done()"  before sending "none" task to the "_failed_tasks" queue. It works forme when i  call a "on_shutdown" method of aiohttp.

**Comment by asvetlov** [comment]
Sorry for the late reply.
Honestly, I didn't get your proposal.

**Comment by obataku** [comment]
@asvetlov consider using aiojobs with an aiohttp web server; if one interrupts the server by pressing Ctrl+C, then the event loop is halted & [`web.run_app`](https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web.py#L437) will cancel all existing tasks (incl. our scheduler's `_failed_task`) before resuming the event loop to allow the tasks to [handle their cancellation](https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web.py#L379).

when the loop is resumed, the app runner is [cleaned up](https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web.py#L368), i.e. [the app cleanup signal is fired](https://github.com/aio-libs/aiohttp/blob/v3.5.4/aiohttp/web_app.py#L398) and registered `on_cleanup` handlers are [executed in sequence](https://github.com/aio-libs/aiohttp/blob/v3.5.4/aiohttp/signals.py#L33)

the problem I encountered when the [`on_cleanup` handler provided by aiojobs](https://github.com/aio-libs/aiojobs/blob/master/aiojobs/aiohttp.py#L47) closes the scheduler, it attempts to [`await _failed_task`](https://github.com/aio-libs/aiojobs/blob/master/aiojobs/_scheduler.py#L100) without checking that the task hasn't yet been cancelled or is otherwise done, causing the handler itself to then raise an exception and preventing any downstream `on_cleanup` handlers from getting a chance to run

calling `setup` after registering one's own cleanup handlers ensures they get called but typically we want to allow atomic/shielded jobs to finish their work *before* cleaning up shared resources they potentially depend on

one can workaround the issue a couple ways, notably by using our own setup routine for the scheduler that consumes the `CancelledError` from `<scheduler>.close()`, but I imagine `await`ing conditionally in [`close`](https://github.com/aio-libs/aiojobs/blob/master/aiojobs/_scheduler.py#L100) is a better solution:

```
if not self._failed_task.done(): # or maybe we can check cancelled() specifically
    await self._failed_task
```

the above will certainly play nicer with aiohttp

**Comment by Dreamsorcerer** [comment]
> @asvetlov consider using aiojobs with aiohttp.web; if one interrupts `run_app` by pressing Ctrl+C, then the event loop is halted & it will [cancel all existing tasks](https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web.py#L437) (incl. our scheduler's `_failed_task`) before resuming the event loop to allow the tasks to [handle their cancellation](https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web.py#L379).
> 
> when the loop is resumed, the app runner is [cleaned up](https://github.com/aio-libs/aiohttp/blob/v3.6.2/aiohttp/web.py#L368), i.e. [the app cleanup signal is fired](https://github.com/aio-libs/aiohttp/blob/v3.5.4/aiohttp/web_app.py#L398) and registered `on_cleanup` handlers are [executed in sequence](https://github.com/aio-libs/aiohttp/blob/v3.5.4/aiohttp/signals.py#L33)

I think you've misread that. The cleanup linked there happens with `_run()` and is therefore happening before the task cancellation in your first paragraph.

If you can produce a test or something that reproduces the issue, we'll revisit it.
